### ISSUE TITLE
BOOSTROOT environment variable missing from modulefile

### ISSUE THREAD

**Issue by guycohen** [sdsc/boost-roll#1]
This environment variable is needed by cmake to find the library. Can be fixed by adding the following line:

setenv BOOSTROOT /opt/boost/gnu

**Comment by tcooper** [comment]
@jerrypgreenberg can you comment/resolve?

**Comment by tcooper** [comment]
Resolved in commit [af28ffa](https://github.com/sdsc/boost-roll/commit/af28ffa). Thanks for reporting.
